version: '2'

services:
  transmart-build:
    build:
      context: ./
      dockerfile: Dockerfile.build
    image: viden/transmart-build
  transmart-run:
    build:
      context: ./
      dockerfile: Dockerfile.run
    image: viden/transmart-run
    volumes:
      - ../transmart-core:/home/transmart-core
  transmart-develop:
    build:
      context: ./
      dockerfile: Dockerfile.develop
    image: viden/transmart-develop
    # volumes:
    # - ../transmart-core:/home/gradle/transmart-core